export class KKHaremGirl {
    id_member: any;
    id_girl: any;
    shards: any;
    level: any;
    fav_graded: any;
    graded: any;
    ts_pay: any;
    affection: any;
    xp: any;
    id_places_of_power: any;
    awakening_level: any;
    date_added: any;
    id_girl_ref: any;
    nb_grades: any;
    class: any;
    figure: any;
    carac1: any;
    carac2: any;
    carac3: any;
    rarity: any;
    salaries: any;
    id_world: any;
    id_quest_get: any;
    images: {
        ava: any[],
        ico: any[]
    }
    element: any;
    name: string;
    release_date: any;
    anniversary: any;
    eye_color1: any;
    eye_color2: any;
    hair_color1: any;
    hair_color2: any;
    upgrade_quests: any;
    scene_paths: any;
    animated_grades: any;
    grade_offset_values: any;
    zodiac: any;
    preview_scenes: any;
    blessing_bonuses: any;
    Affection: any;
    can_upgrade: any;
    Graded: any;
    graded2: any;
    ico: any;
    avatar: any;
    black_avatar: any;
    armor: any;
    caracs: any;
    skill_tiers_info: any;
    grade_offsets: any;
    caracs_sum: any;
    orgasm: any;
    style: any;
    element_data: any;
    position_img: any;
    level_cap: any;
    salary: any;
    pay_time: any;
    pay_in: any;
    salary_per_hour: any;
    Xp: any;
    preview: any;
    awakening_costs: any;
    upgrade_link: any;
}